image:
  file: .gitpod.Dockerfile

tasks:
  - command: projen dev

ports:
    - name: Backend
      port: 8000
      onOpen: open-browser
    
github:
    prebuilds:
        master: true
        pullRequests: false
        addComment: false