name: Create and publish a Docker image

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  WORKLOAD_IDENTITY_PROVIDER: projects/70756149774/locations/global/workloadIdentityPools/my-pool/providers/my-provider
  SERVICE_ACCOUNT: hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com
  ORGANIZATION: hs-heilbronn-devsecops-kydd
  PROJECT_ID: hs-heilbronn-devsecops
  LOCATION: europe-west3
  GITHUB_IMAGE_TAG: sha-85e2173
  GCR_REGISTRY: gcr.io
  GCR_IMAGE_NAME: gcr.io/hs-heilbronn-devsecops/taskman

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
               

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Pull image from GitHub Container Registry
        run: docker pull "${REGISTRY}/${IMAGE_NAME}:${GITHUB_IMAGE_TAG}"
       
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
            workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ env.SERVICE_ACCOUNT}}


      - name: List Docker images
        run: |
          docker images

#      - name: Tag and push image to Google Container Registry
#        run: |
#          docker tag "${REGISTRY}/${IMAGE_NAME}:${GITHUB_IMAGE_TAG}" "${GCR_REGISTRY}/${PROJECT_ID}:${GITHUB_IMAGE_TAG}"
#          docker push "${GCR_REGISTRY}/${PROJECT_ID}:${GITHUB_IMAGE_TAG}"

#      - name: Pull image from GitHub Container Registry and push to Google Container Registry
#        run: |
#          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} ${{ env.GCR_IMAGE_NAME }}
#          docker push ${{ env.GCR_IMAGE_NAME }}
           
      - name: Deploy
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'taskman-${{ env.ORGANIZATION }}'
          image: '${{ env.GCR_IMAGE_NAME }}'
          backend: 'memory'

      - name: Create GCS bucket
        run: |
          gcloud auth activate-service-account --key-file=${{ env.SERVICE_ACCOUNT }}
          gsutil mb gs://kydd-bucket

      - name: Update Cloud Run service with GCS backend
        run: |
          gcloud run services update 'taskman-${{ env.ORGANIZATION }}' --region=${{ env.LOCATION }} --update-env-vars=BACKEND=gcs



