name: Check with linter on PR

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pylint
        run: pip install pylint
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pylint
        run: pylint taskman
      - name: Run tests
        run: pytest -n auto
      - name: Run tests with coverage
        run: pytest --cov=taskman tests/
      - name: Authenticate Snyk with Github
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Snyk security scan
        uses: snyk/actions/python@master
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}


# adbf8706-f8f9-4632-9b7d-56668c3136df